MVCAvisaEnchenteProject/Models/Entidades/PontoDeSensoriamento.cs
using MVCAvisaEnchenteProject.Models.ViewModels.PontoDeSensoriamentoModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCAvisaEnchenteProject.Models.Entidades
{
    public class PontoDeSensoriamento : BaseEntity
    {
        public string HelixId { get; set; }
        public bool AtivoHelix { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public int CidadeAtendidaId { get; set; }
        public int UsuarioId { get; set; }
        public CidadeAtendida CidadeAtendida { get; set; }
        public EstadoAtendido EstadoAtendido { get; set; }
        public RegistroSensoriamento SensoriamentoAtual { get; set; }
        public Usuario Usuario { get; set; }

        public PontoDeSensoriamento(CriarEditarPontoDeSensoriamentoViewModel pontoDeSensoriamentoViewModel, int cidadeAtendidaId, int usuarioId) : base(pontoDeSensoriamentoViewModel.Id)
        {
            HelixId = $"urn:ngsi-ld:sensor:{pontoDeSensoriamentoViewModel.HelixId}";
            AtivoHelix = pontoDeSensoriamentoViewModel.Ativo;
            Latitude = Convert.ToDecimal(pontoDeSensoriamentoViewModel.Latitude.Replace(".", ","));
            Longitude = Convert.ToDecimal(pontoDeSensoriamentoViewModel.Longitude.Replace(".", ","));
            CidadeAtendidaId = cidadeAtendidaId;
            UsuarioId = usuarioId;
        }
        public PontoDeSensoriamento()
        { 
        
        }
    }
}

MVCAvisaEnchenteProject/Controllers/PontoDeSensoriamentoController.cs
using Integracoes;
using Integracoes.Api;
using Integracoes.Models.Geocode;
using Integracoes.Models.Helix.PontoDeSensoriamento;
using Integracoes.Models.IBGE;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCAvisaEnchenteProject.Infrastructure.DAO;
using MVCAvisaEnchenteProject.Infrastructure.Helpers;
using MVCAvisaEnchenteProject.Models.Entidades;
using MVCAvisaEnchenteProject.Models.Enum;
using MVCAvisaEnchenteProject.Models.ViewModels;
using MVCAvisaEnchenteProject.Models.ViewModels.GoogleMaps;
using MVCAvisaEnchenteProject.Models.ViewModels.ParametrosNotificacao;
using MVCAvisaEnchenteProject.Models.ViewModels.PontoDeSensoriamentoModels;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Transactions;

namespace MVCAvisaEnchenteProject.Controllers
{
    public class PontoDeSensoriamentoController : BaseController<PontoDeSensoriamento, PontoDeSensoriamentoDAO>
    {
        private readonly IntegracaoIBGE _integracaoIBGE;
        private readonly IntegracaoGeocode _integracaoGeocode;
        private readonly IntegracaoHelix _integracaoHelix;
        private readonly EstadoAtendidoDAO _estadoAtendidoDAO;
        private readonly CidadeAtendidaDAO _cidadeAtendidaDAO;
        private readonly ParametroNotificacaoDAO _parametroNotificaoDAO;
        private readonly RegistroSensoriamentoDAO _registroSensoriamentoDAO;

        public PontoDeSensoriamentoController() : base()
        {
            _integracaoIBGE = new IntegracaoIBGE(new IBGEApi());
            _integracaoGeocode = new IntegracaoGeocode(new GeoCodeApi());
            _integracaoHelix = new IntegracaoHelix(new HelixApi());
            _estadoAtendidoDAO = new EstadoAtendidoDAO();
            _cidadeAtendidaDAO = new CidadeAtendidaDAO();
            _parametroNotificaoDAO = new ParametroNotificacaoDAO();
            _registroSensoriamentoDAO = new RegistroSensoriamentoDAO();

        }

        [HttpGet]
        [Authorize(Roles = nameof(ETipoUsuario.Admin))]
        public override IActionResult Index(int id)
        {
            var indexViewModel = new IndexPontoDeSensoriamentoViewModel(DAOPrincipal.Listar());
            return View(indexViewModel);
        }

        [HttpGet]
        [Authorize(Roles = nameof(ETipoUsuario.Admin))]
        public IActionResult CriarOuEditarPontoDeSensoriamento(int id = 0)
        {
            if (id == 0)
                return View(new CriarEditarPontoDeSensoriamentoViewModel());

            var pontoDeSensoriamento = DAOPrincipal.ConsultarPorId(id);
            if (pontoDeSensoriamento != null)
            {      
                return View(new CriarEditarPontoDeSensoriamentoViewModel(pontoDeSensoriamento));
            }

            TempData["Error"] = "Ponto de Sensoriamento não existe!";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = nameof(ETipoUsuario.Admin))]
        public async Task<IActionResult> SalvarPontoDeSensoriamento(int id, [Bind("Id, HelixId, Ativo, CodigoEstado, CodigoCidade, Latitude, Longitude")] CriarEditarPontoDeSensoriamentoViewModel pontoDeSensoriamentoViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    using (var transacao = new System.Transactions.TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                    {
                        #region Valida e Atualiza Informações da Cidade e Estado no Banco

                        var (jsonResponse, cidadeAtendidaId) = await AtualizaInfosEstadoECidade(pontoDeSensoriamentoViewModel.CodigoEstado,
                                                                                                pontoDeSensoriamentoViewModel.CodigoCidade,
                                                                                                pontoDeSensoriamentoViewModel.Latitude,
                                                                                                pontoDeSensoriamentoViewModel.Longitude);
                        if (jsonResponse.Erro)
                            return Json(jsonResponse);

                        #endregion


                        var pontoDeSensoriamento = new PontoDeSensoriamento(pontoDeSensoriamentoViewModel, cidadeAtendidaId: cidadeAtendidaId, usuarioId: Convert.ToInt32(ObterIdUsuarioLogado()));

                        var integracaoHelixResponse = await SalvaPontoDeSensoriamentoHelix(pontoDeSensoriamento: pontoDeSensoriamento);
                        if (integracaoHelixResponse.Erro)
                        {
                            return Json(integracaoHelixResponse);
                        }

                        if (id == 0)
                        {
                            DAOPrincipal.Inserir(pontoDeSensoriamento);
                        }
                        else
                        {
                            if (DAOPrincipal.ConsultarPorId(id) != null)
                                DAOPrincipal.Atualizar(pontoDeSensoriamento);
                            else
                                return Json(new JsonResponse(messageErro: "Ponto de Sensoriamento não encontrado!"));
                        }

                        transacao.Complete();
                    }
                    return Json(new JsonResponse(valido: true));
                }
                catch (Exception e)
                {
                    return Json(new JsonResponse(messageErro: "Ocorreu um erro ao tentar salvar o Ponto de Sensoriamento!"));
                }
            }
            return Json(new JsonResponse(valido: false, html: HelperRenderRazorView.RenderRazorViewToString(this, "CriarOuEditarPontoDeSensoriamento", pontoDeSensoriamentoViewModel)));
        }

        [HttpPost]
        public async Task<JsonResponse> SalvaPontoDeSensoriamentoHelix(PontoDeSensoriamento pontoDeSensoriamento = null, int? id = null)
        {
            RestResponse helixUpsertResponse = null;
            if(string.IsNullOrEmpty(pontoDeSensoriamento?.HelixId) && id.HasValue)
            {
                pontoDeSensoriamento = DAOPrincipal.ConsultarPorId(id.Value);
            }

            var consultaEntidadeHelix = await _integracaoHelix.GetEntityById<PontoDeSensoriamentoHelixEntity>(pontoDeSensoriamento.HelixId);
            var pontoDeSensoriamentoHelixEntity = new PontoDeSensoriamentoHelixEntity(id: pontoDeSensoriamento.HelixId);

            if (pontoDeSensoriamento.Id == 0)
            {
                var existePDScomHelixId = DAOPrincipal.PontoDeSensoriamentoJaExiste(pontoDeSensoriamento.HelixId);
                if (consultaEntidadeHelix != null || existePDScomHelixId)
                    return new JsonResponse(messageErro: "Entidade já Cadastrada no Helix!");

            }
            if (consultaEntidadeHelix == null)
                helixUpsertResponse = await _integracaoHelix.CreateEntity<PontoDeSensoriamentoHelixEntity>(pontoDeSensoriamentoHelixEntity);


            if (helixUpsertResponse != null && helixUpsertResponse.IsSuccessful)
            {
                pontoDeSensoriamento.AtivoHelix = true;
                if (id.HasValue)
                    DAOPrincipal.Atualizar(pontoDeSensoriamento);

                return new JsonResponse(valido: true);
            }

            return new JsonResponse(valido: false);
        }

        private async Task<(JsonResponse JsonResponse, int CidadeAtendidaId)> AtualizaInfosEstadoECidade(string codigoEstado, string codigoCidade, string latitude, string longitude )
        {
            EstadoAtendido estadoAtendido;
            CidadeAtendida cidadeAtendida;
            int cidadeAtendidaId;

            try
            {
                var estadoSelecionado = await _integracaoIBGE.ObterEstadoPorCodigo(codigoEstado);
                var cidadeSelecionada = await _integracaoIBGE.ObterCidadePorCodigo(codigoCidade);

                var localizacaoValida = await ValidaLocalizacao(estadoSelecionado, cidadeSelecionada, latitude, longitude);
                if(localizacaoValida.Erro)
                    return (JsonResponse: localizacaoValida, CidadeAtendidaId: 0);


                estadoAtendido = _estadoAtendidoDAO.ConsultaEstadoPorCodigo(codigoEstado);
                cidadeAtendida = _cidadeAtendidaDAO.ConsultaCidadePorCodigo(codigoCidade);

                int estadoAtendidoId;
                if (estadoAtendido == null)
                {
                    estadoAtendido = new EstadoAtendido(estadoSelecionado.Nome, estadoSelecionado.Id.ToString(), estadoSelecionado.Sigla);
                    estadoAtendidoId = _estadoAtendidoDAO.ProximoId();
                    _estadoAtendidoDAO.Inserir(estadoAtendido);
                }
                else
                    estadoAtendidoId = estadoAtendido.Id;

                if (cidadeAtendida == null)
                {
                    cidadeAtendida = new CidadeAtendida(cidadeSelecionada.Nome, cidadeSelecionada.Id.ToString(), estadoAtendidoId);
                    cidadeAtendidaId = _cidadeAtendidaDAO.ProximoId();
                    _cidadeAtendidaDAO.Inserir(cidadeAtendida);
                }
                else
                    cidadeAtendidaId = cidadeAtendida.Id;


                return (JsonResponse: new JsonResponse(), CidadeAtendidaId: cidadeAtendidaId);
            }
            catch (Exception e)
            {
                return (JsonResponse: new JsonResponse(messageErro: "Ocorreu um erro ao tentar salvar a cidade ou estado!"), CidadeAtendidaId: 0);
            }
        }

        private async Task<JsonResponse> ValidaLocalizacao(Estado estadoSelecionado, Municipio cidadeSelecionada, string latitude, string longitude)
        {
            if (latitude.Contains(",") || longitude.Contains(","))

MVCAvisaEnchenteProject/Views/PontoDeSensoriamento/CriarOuEditarPontoDeSensoriamento.cshtml
@model CriarEditarPontoDeSensoriamentoViewModel

@{
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <form method="post" id="form-criar-editar-ponto-de-sensoriamento" asp-action="SalvarPontoDeSensoriamento" asp-route-id="@Model.Id" onsubmit="return salvarAjax(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Ativo" />
            <div class="form-group">
                <label asp-for="HelixId" class="control-label text-primary"></label>
                <div class="input-group input-group-sm">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">urn:ngsi-ld:sensor:</span>
                    </div>
                    <input type="text" asp-for="HelixId" class="form-control form-control-sm" placeholder="Helix Id" aria-describedby="basic-addon1" />
                </div>
                <span asp-validation-for="HelixId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoEstado" class="control-label text-primary"></label>
                <div id="estados">
                    @Html.DropDownListFor(m => m.CodigoEstado, new List<SelectListItem>(), "Selecione o Estado...", new { @class = "form-control form-control-sm", @id = "selectEstados" })
                </div>
                <span asp-validation-for="CodigoEstado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoCidade" class="control-label text-primary"></label>
                <div id="municipios">
                    @Html.DropDownListFor(m => m.CodigoCidade, new List<SelectListItem>(), "Selecione a Cidade...", new { @class = "form-control form-control-sm", @id = "selectCidades" })
                </div>
                <span asp-validation-for="CodigoCidade" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label text-primary"></label>
                <input type="text" asp-for="Latitude" class="form-control form-control-sm geolocalizacao-input" placeholder="Latitude" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label text-primary"></label>
                <input type="text" asp-for="Longitude" class="form-control form-control-sm geolocalizacao-input" placeholder="Longitude" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>

            <div class="modal-footer" style="padding: 10px 0 0px; margin-top: 40px;">
                <button type="button" class="btn btn-dark" data-dismiss="modal">Fechar</button>
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<script>
    $(document).ready(function () {
            realizaBuscaEstados();
            realizaBuscaCidades();
            $(".geolocalizacao-input").numeric({ decimal: ".", decimalPlaces: 9 });
    });

        realizaBuscaEstados = () => {
            $.ajax({
                type: 'GET',
                url: "/Localizacao/ObtemSelectListEstados",
                datatype: 'JSON',
                traditional: true,
                async: true,
                success: function (data) {
                    var estadosHtml = "<select class='form-control form-control-sm' id='selectEstados' name='CodigoEstado'>";
                    estadosHtml = estadosHtml + '<option value="">Selecione o Estado...</option>';
                    for (var i = 0; i < data.length; i++) {
                        estadosHtml = estadosHtml + '<option value=' + data[i].value + '>' + data[i].text + '</option>';
                    }
                    estadosHtml = estadosHtml + '</select>';
                    $('#estados').html(estadosHtml);
                    $('#selectEstados').val('@Model.CodigoEstado')
                    $('#selectEstados').change(() => realizaBuscaCidades());
                }
            })

        };

    realizaBuscaCidades = () => {
        let value = '@Model.CodigoEstado' !== '' ? '@Model.CodigoEstado' : $('#selectEstados').val();
        $.ajax({
            type: 'GET',
            url: "/Localizacao/ObtemSelectListCidadesPorUF",
            data: { estado: value },
            datatype: 'JSON',
            traditional: true,
            async: true,
            success: function (data) {
                var municipiosHtml = "<select class='form-control form-control-sm' id='selectCidades' name='CodigoCidade'>";
                municipiosHtml = municipiosHtml + '<option value="">Selecione a Cidade...</option>';
                for (var i = 0; i < data.length; i++) {
                    municipiosHtml = municipiosHtml + '<option value=' + data[i].value + '>' + data[i].text + '</option>';
                }
                municipiosHtml = municipiosHtml + '</select>';
                $('#municipios').html(municipiosHtml);
                $('#selectCidades').val('@Model.CodigoCidade')
            }
        })
    };

</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCAvisaEnchenteProject/Views/PontoDeSensoriamento/Index.cshtml
@model IndexPontoDeSensoriamentoViewModel

@{
    ViewData["Title"] = "Pontos De Sensoriamento";
}

<h4 class="text-primary pt-3">@ViewData["Title"]</h4>

<div id="pv-pesquisa-avancada-usuarios" class="my-3">
        @await Html.PartialAsync("_FormPesquisaAvancadaPontosDeSensoriamento", Model.PesquisaAvancadaPontosDeSensoriamento)
</div>

<div id="pv-listar-pontos-sensoriamento">
    @await Html.PartialAsync("_ListarPontosDeSensoriamento", Model.PontoDeSensoriamentos)
</div>

@section Scripts {
    <script src="~/js/configurations.js"></script>

    <script>
        $(document).ready(function () {
            realizaBuscaEstadosAtendidas();
            realizaBuscaUsuariosAdmin();
            ChangeIconButtonFiltro();
        });

        realizaBuscaEstadosAtendidas = () => {
            $.ajax({
                type: 'GET',
                url: "/Localizacao/ObtemSelectListEstadosAtendidos",
                datatype: 'JSON',
                traditional: true,
                async: false,
                success: function (data) {
                    var estadosHtml = "<select class='form-control form-control-sm' id='selectEstadoAtendido' name='EstadoId'>";
                    estadosHtml = estadosHtml + '<option value="">Selecione o Estado...</option>';
                    for (var i = 0; i < data.length; i++) {
                        estadosHtml = estadosHtml + '<option value=' + data[i].value + '>' + data[i].text + '</option>';
                    }
                    estadosHtml = estadosHtml + '</select>';
                    $('#estados-atendidos').html(estadosHtml);
                    $('#selectEstadoAtendido').val(@Model.PesquisaAvancadaPontosDeSensoriamento.EstadoId)
                    $('#selectEstadoAtendido').change(() => realizaBuscaCidadesAtendidas());
                }
            })
        };

        realizaBuscaCidadesAtendidas = () => {
            $.ajax({
                type: 'GET',
                url: "/Localizacao/ObtemSelectListCidadesAtendidasPorEstadoId",
                data: { estado: $('#selectEstadoAtendido').val() },
                datatype: 'JSON',
                traditional: true,
                async: false,
                success: function (data) {
                    var municipiosHtml = "<select class='form-control form-control-sm' id='selectCidadeAtendida' name='CidadeId'>";
                    municipiosHtml = municipiosHtml + '<option value="">Selecione a Cidade...</option>';
                    for (var i = 0; i < data.length; i++) {
                        municipiosHtml = municipiosHtml + '<option value=' + data[i].value + '>' + data[i].text + '</option>';
                    }
                    municipiosHtml = municipiosHtml + '</select>';
                    $('#municipios-atendidos').html(municipiosHtml);
                    $('#selectCidadeAtendida').val(@Model.PesquisaAvancadaPontosDeSensoriamento.CidadeId)
                }
            })
        };

        realizaBuscaUsuariosAdmin = () => {
            $.ajax({
                type: 'GET',
                url: "/Usuario/ObtemSelectListUsuariosAdmin",
                datatype: 'JSON',
                traditional: true,
                async: false,
                success: function (data) {
                    var usuariosHtml = "<select class='form-control form-control-sm' id='selectUsuariosAdmin' name='UsuarioId'>";
                    usuariosHtml = usuariosHtml + '<option value="">Selecione o Usuário...</option>';
                    for (var i = 0; i < data.length; i++) {
                        usuariosHtml = usuariosHtml + '<option value=' + data[i].value + '>' + data[i].text + '</option>';
                    }
                    usuariosHtml = usuariosHtml + '</select>';
                    $('#usuarios-admin').html(usuariosHtml);
                    $('#selectUsuariosAdmin').val(@Model.PesquisaAvancadaPontosDeSensoriamento.UsuarioId)
                }
            })
        };

    </script>
}

MVCAvisaEnchenteProject/Views/PontoDeSensoriamento/_FormPesquisaAvancadaPontosDeSensoriamento.cshtml
@model PesquisaAvancadaPontosDeSensoriamento


<div id="accordion">
    <div class="w-100">
        <button onclick="ChangeIconButtonFiltro()" class="btn btn-sm btn-primary mb-2" style="width: 100%; max-width: 90px; font-size: 1rem" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            Filtros <i id="filtrar-collapse-icon" class="fa-solid fa-caret-up ml-2 showing-collapse"></i>
        </button>
        <a onclick="abrirFormModal('@Url.Action("CriarOuEditarPontoDeSensoriamento", "PontoDeSensoriamento", null, Context.Request.Scheme)', 'Cadastrar Ponto de Sensoriamento')" class="btn btn-primary btn-sm text-white mb-2 float-end" style="width: 100%; max-width: 18rem; font-size: 1rem; text-align: center"><i class="fa-solid fa-plus mr-1"></i>Cadastrar Ponto de Sensoriamento</a>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
        <div class="card">
            <div class="card-body">
                <h6 class="text-primary">Filtrar por: </h6>
                <form asp-action="PesquisaAvancadaPontosDeSensoriamento" onsubmit="return realizaPesquisaAvancada(this);" id="pesquisa-avancada-pontos-de-sensoriamento">
                    <div class="row">

                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="HelixId" class="control-label text-primary"></label>
                                <div class="input-group input-group-sm">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon2">urn:ngsi-ld:entity:</span>
                                    </div>
                                    <input asp-for="HelixId" class="form-control form-control-sm" placeholder="Helix Id" aria-describedby="basic-addon2" />
                                </div>
                            </div>
                        </div>

                        <div class="col-md-2">
                            <div class="form-group">
                                <label asp-for="Ativo" class="control-label text-primary"></label>
                                <select class='form-control form-control-sm' asp-for="Ativo">
                                    <option value="">Selecione</option>
                                    <option value="true">Sim</option>
                                    <option value="false">Não</option>
                                </select>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="UsuarioId" class="control-label text-primary"></label>
                                <div id="usuarios-admin">
                                    @Html.DropDownListFor(m => m.UsuarioId, new List<SelectListItem>(), "Selecione o Usuário...", new { @class = "form-control form-control-sm", @id = "selectUsuariosAdmin" })
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">

                        <div class="col-md-3">
                            <div class="form-group">
                                <label asp-for="EstadoId" class="control-label text-primary"></label>
                                <div id="estados-atendidos">
                                    @Html.DropDownListFor(m => m.EstadoId, new List<SelectListItem>(), "Selecione o Estado...", new { @class = "form-control form-control-sm", @id = "selectEstadoAtendido" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label asp-for="CidadeId" class="control-label text-primary"></label>
                                <div id="municipios-atendidos">
                                    @Html.DropDownListFor(m => m.CidadeId, new List<SelectListItem>(), "Selecione a Cidade...", new { @class = "form-control form-control-sm", @id = "selectCidadeAtendida" })
                                </div>
                            </div>
                        </div>

                        <div class="col-md-5" style="padding-top: 2rem; text-align: end">
                            <div class="form-group">
                                <button type="submit" value="Pesquisar" style="width: 100%; max-width: 140px" class="btn btn-primary btn-sm">
                                    <i class="fa-solid fa-filter mr-1"></i>
                                    Filtrar
                                </button>
                                <button type="reset" value="Limpar" style="width: 100%; max-width: 100px" class="btn btn-outline-secondary btn-sm ">
                                    <i class="fa-solid fa-eraser mr-1"></i>
                                    Limpar
                                </button>
                            </div>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MVCAvisaEnchenteProject/Views/PontoDeSensoriamento/_ListarPontosDeSensoriamento.cshtml
@model IEnumerable<PontoDeSensoriamento>

<div class="card">
    <div class="card-header text-primary"><h5> Pontos de Sensoriamento </h5></div>
    <div class="card-body">
        <table class="table-sm table-striped table-responsive-xl"
               id="table"
               data-toggle="table"
               data-pagination="true"
               data-page-list="[5, 10, 15, 20, 25, 50, 100, ALL]">
            <thead>
                <tr>
                    <th data-field="id" data-sortable="true" data-width="5" data-width-unit="%">Id</th>
                    <th data-field="helix-id" data-sortable="true" data-width="19" data-width-unit="%">Helix Id</th>
                    <th data-field="ativo-helix" data-sortable="true" data-width="5" data-width-unit="%">Ativo</th>
                    <th data-field="tipo-usuario" data-sortable="true" data-width="20" data-width-unit="%">Última Edição Por:</th>
                    <th data-field="estado" data-sortable="true" data-width="5" data-width-unit="%">Estado</th>
                    <th data-field="cidade" data-sortable="true" data-width="20" data-width-unit="%">Cidade</th>
                    <th data-field="acoes" data-width="26" data-width-unit="%">Ações</th>
                </tr>
            </thead>
            <tbody style=" font-size: 0.9rem;">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Id
                        </td>
                        <td>
                            @item.HelixId
                        </td>
                        <td style="text-align: center">
                            @if (!item.AtivoHelix)
                            {

                                <a onclick="ativaPontoDeSensoriamento('@Url.Action("SalvaPontoDeSensoriamentoHelix", "PontoDeSensoriamento", null, Context.Request.Scheme)', @item.Id)" class="btn icon text-danger" title="Desativado"><i class="fa-solid fa-signal fa-xl"></i></a>
                            }
                            else
                            {
                                <a class="btn icon text-success" title="Ativado"><i class="fa-solid fa-signal fa-xl"></i></a>
                            }
                        </td>
                        <td>
                            @item.Usuario.NomeCompleto
                        </td>
                        <td>
                            @item.EstadoAtendido.UF
                        </td>
                        <td>
                            @item.CidadeAtendida.Descricao
                        </td>
                        <td>
                            <a asp-controller="PontoDeSensoriamento" asp-action="Detalhes" asp-route-id="@item.Id" class="btn btn-info btn-sm text-white" role="button"><i class="fa-solid fa-circle-info mr-1"></i>Detalhes</a>
                            <a onclick="abrirFormModal('@Url.Action("CriarOuEditarPontoDeSensoriamento", "PontoDeSensoriamento", new {id=item.Id}, Context.Request.Scheme)', 'Editar Ponto De Sensoriamento')" class="btn btn-warning btn-sm text-white" role="button"><i class="fa-solid fa-pen-to-square mr-1"></i>Editar</a>
                            <a onclick="deletarPorIdEController(@item.Id, 'PontoDeSensoriamento')" class="btn btn-danger btn-sm text-white" role="button"><i class="fa-solid fa-trash mr-1"></i>Excluir</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>