MVCAvisaEnchenteProject/Controllers/ContaController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCAvisaEnchenteProject.Infrastructure.DAO;
using MVCAvisaEnchenteProject.Infrastructure.Helpers;
using MVCAvisaEnchenteProject.Models.Entidades;
using MVCAvisaEnchenteProject.Models.Enum;
using MVCAvisaEnchenteProject.Models.ViewModels;
using MVCAvisaEnchenteProject.Models.ViewModels.UsuarioModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MVCAvisaEnchenteProject.Controllers
{
    public class ContaController : BaseController<Usuario, UsuarioDAO>
    {
        public ContaController()
        {
            DAOPrincipal = new UsuarioDAO();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Registro()
        {
            if (!UsuarioEstaLogado())
                return View(new RegistrarUsuarioViewModel());

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Registro(RegistrarUsuarioViewModel usuarioModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var usuario = new Usuario(usuarioModel);
                    if (DAOPrincipal.EmailJaExiste(usuarioModel.Email))
                    {
                        TempData["Error"] = "Erro ao Cadastrar Usuário";
                        return View(usuarioModel);
                    }

                    DAOPrincipal.Inserir(usuario);

                    TempData["Success"] = "Usuário Cadastrado Com Sucesso!";
                    return RedirectToAction("Login");
                }
                catch (Exception erro)
                {
                    return View("Error", new ErrorViewModel(erro.ToString()));
                }
            }

            return View(usuarioModel);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login() 
        {
            if(!UsuarioEstaLogado())
                return View(new LoginUsuarioRequest());

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public IActionResult Login(LoginUsuarioRequest login)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var usuario = DAOPrincipal.LogarUsuario(login);

                    if (usuario != null)
                    {
                        var userClaims = new List<Claim>()
                        {
                            new Claim("UsuarioId", usuario.Id.ToString()),
                            new Claim(ClaimTypes.Name, usuario.NomeCompleto),
                            new Claim(ClaimTypes.Email, usuario.Email),
                            new Claim(ClaimTypes.Role, usuario.TipoUsuario.GetDescription())
                        };
                        var userIdentity = new ClaimsIdentity(userClaims, "User Identity");

                        var userPrincipal = new ClaimsPrincipal(new[] { userIdentity });
                        HttpContext.SignInAsync(userPrincipal);
                        HttpContext.Session.SetString("ImagemPerfilBase64", usuario.ImagemDePerfilEmBase64);

                        if (usuario.PrimeiroLogin)
                            return RedirectToAction("PrimeiroLogin");

                        return RedirectToAction("Index", "Home");
                    }

                    TempData["Error"] = "Falha no Login, Email ou Senha Incorretos!";
                }
                catch (Exception erro)
                {
                    return View("Error", new ErrorViewModel(erro.ToString()));
                }

            }

            return View(login);
        }

        [HttpGet]
        [Authorize]
        public IActionResult PrimeiroLogin()
        {
            return View(new PrimeiroLoginViewModel());
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult PrimeiroLogin(PrimeiroLoginViewModel primeiroLogin)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var usuarioId = User.FindFirst("UsuarioId").Value;
                    DAOPrincipal.DefineCidadeUsuario(Convert.ToInt32(usuarioId), primeiroLogin.CidadeAtendidaId);
                    HttpContext.Session.Remove("PrimeiroLogin");

                    return RedirectToAction("Index", "Home");
                }
                catch (Exception erro)
                {
                    return View("Error", new ErrorViewModel(erro.ToString()));
                }
            }

            return View(primeiroLogin);
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MVCAvisaEnchenteProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCAvisaEnchenteProject.Infrastructure.CustomAttributes;
using MVCAvisaEnchenteProject.Infrastructure.DAO;
using MVCAvisaEnchenteProject.Models.Entidades;
using MVCAvisaEnchenteProject.Models.ViewModels;
using MVCAvisaEnchenteProject.Models.ViewModels.GoogleMaps;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCAvisaEnchenteProject.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly UsuarioDAO _usuarioDAO;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
            _usuarioDAO = new UsuarioDAO();
        }

        [Route("/")]
        [AllowAnonymous]
        public IActionResult Index()
        {
            if (!string.IsNullOrEmpty(HttpContext.User.FindFirst("UsuarioId")?.Value))
                return RedirectToAction("Index", "SensoriamentoAtual");

            return View();
        }

        public IActionResult SobreNos()
        {
            return View();
        }
        public IActionResult ComoFunciona()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult NotFoundPageView()
        {
            return View();
        }

        [AllowAnonymous]
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCAvisaEnchenteProject/Views/Home/ComoFunciona.cshtml
@{
    ViewData["Title"] = "Como Funciona?";
}

<h3 class="text-primary pt-3">@ViewData["Title"]</h3>

@section Scripts {
    <script>
        window.addEventListener('load', function () {

            $('#index').removeClass('active');
            $('#sobre-nos').removeClass('active');
            $('#como-funciona').addClass('active');
            $('#meu-perfil-image').removeClass('active');
            $('#configuracoes').removeClass('active');

        });
    </script>
}

MVCAvisaEnchenteProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="row" style=" height: calc(100vh - 10vh);">
    <div class="col-md-6 my-auto tela-inicial-text">
        <h1 class="text-primary font-weight-bold">
            Um Website de
            Monitoramento de
            Enchentes e Alagamentos
        </h1>
        <div class="text-dark mb-4">
            Nosso sistema consegue identificar em
            pontos estratégios, possiveis riscos de enchentes
            e alagamentos em tempo real!
        </div>
        <a class="btn btn-primary btn-entrar-tela-inicial" asp-controller="Conta" asp-action="Login">Entrar</a>
        <div class="text-dark fa-1x nao-possui-conta-text">Não Possui uma conta? <a class="link-text" href="/conta/registro">Cadastre-se</a></div>
    </div>
</div>
<div class="tela-inicial-image d-none d-md-block">
    <img src="/img/tela-inicial-image.jpg" />
</div>

@section Scripts {
    <script src="~/js/pagina-inicial.js"></script>
}

MVCAvisaEnchenteProject/Views/Home/SobreNos.cshtml
@{
    ViewData["Title"] = "Sobre Nós";
}

<h3 class="text-primary pt-3">@ViewData["Title"]</h3>

<p>Abrão Astério Junior RA: 081200035</p>
<p>Alexandre Bezerra RA: 081200034</p>
<p>Cayo Vinicius RA: 081200050</p>
<p>Daniel Santos de Sousa RA: 081200021</p>
<p>Francisco Silveira RA: 081200018</p>


@section Scripts {
    <script>
        window.addEventListener('load', function () {

            $('#index').removeClass('active');
            $('#sobre-nos').addClass('active');
            $('#como-funciona').removeClass('active');
            $('#meu-perfil-image').removeClass('active');
            $('#configuracoes').removeClass('active');

        });
    </script>
}

MVCAvisaEnchenteProject/Views/Home/_PaginaInicialUsuarioNaoLogado.cshtml
@{
    Layout = null;
}


<div class="row" style=" height: calc(100vh - 10vh);">
    <div class="col-md-6 my-auto tela-inicial-text">
        <h1 class="text-primary font-weight-bold">
            Um Website de
            Monitoramento de
            Enchentes e Alagamentos
        </h1>
        <div class="text-dark mb-4">
            Nosso sistema consegue identificar em
            pontos estratégios, possiveis riscos de enchentes
            e alagamentos em tempo real!
        </div>
        <a class="btn btn-primary btn-entrar-tela-inicial" asp-controller="Conta" asp-action="Login">Entrar</a>
        <div class="text-dark fa-1x nao-possui-conta-text">Não Possui uma conta? <a class="link-text" href="/conta/registro">Cadastre-se</a></div>
    </div>
</div>
<div class="tela-inicial-image d-none d-md-block">
    <img src="/img/tela-inicial-image.jpg" />
</div>